using System.IO;
using System.Collections.Generic;
using BIEM.Tools;
using System;

namespace BIEM.OutputReporting
{
    public enum VariableNameType
    {
        AirSystemComponentModelSimulationCalls,
        AirSystemReliefAirTotalHeatLossEnergy,
        AirSystemSimulationIterationCount,
        AirSystemSimulationMaximumIterationCount,
        AirSystemSolverIterationCount,
        DebugSurfaceSolarShadingModelDifShdgRatioHoriz,
        DebugSurfaceSolarShadingModelDifShdgRatioIsoSky,
        DebugSurfaceSolarShadingModelWithShdgIsoSky,
        DebugSurfaceSolarShadingModelWoShdgIsoSky,
        ElectricEquipmentConvectiveHeatingEnergy,
        ElectricEquipmentConvectiveHeatingRate,
        ElectricEquipmentElectricityEnergy,
        ElectricEquipmentElectricityRate,
        ElectricEquipmentLatentGainEnergy,
        ElectricEquipmentLatentGainRate,
        ElectricEquipmentLostHeatEnergy,
        ElectricEquipmentLostHeatRate,
        ElectricEquipmentRadiantHeatingEnergy,
        ElectricEquipmentRadiantHeatingRate,
        ElectricEquipmentTotalHeatingEnergy,
        ElectricEquipmentTotalHeatingRate,
        EnvironmentalImpactTotalCH4EmissionsCarbonEquivalentMass,
        EnvironmentalImpactTotalCO2EmissionsCarbonEquivalentMass,
        EnvironmentalImpactTotalN2OEmissionsCarbonEquivalentMass,
        FacilityAllZonesVentilationAtTargetVozTime,
        FacilityAnyZoneOscillatingTemperaturesDuringOccupancyTime,
        FacilityAnyZoneOscillatingTemperaturesinDeadbandTime,
        FacilityAnyZoneOscillatingTemperaturesTime,
        FacilityAnyZoneVentilationAboveTargetVozTime,
        FacilityAnyZoneVentilationBelowTargetVozTime,
        FacilityAnyZoneVentilationWhenUnoccupiedTime,
        FacilityCoolingSetpointNotMetTime,
        FacilityCoolingSetpointNotMetWhileOccupiedTime,
        FacilityHeatingSetpointNotMetTime,
        FacilityHeatingSetpointNotMetWhileOccupiedTime,
        FacilityNetPurchasedElectricityEnergy,
        FacilityNetPurchasedElectricityRate,
        FacilityThermalComfortASHRAE55SimpleModelSummerClothesNotComfortableTime,
        FacilityThermalComfortASHRAE55SimpleModelSummerorWinterClothesNotComfortableTime,
        FacilityThermalComfortASHRAE55SimpleModelWinterClothesNotComfortableTime,
        FacilityTotalBuildingElectricityDemandRate,
        FacilityTotalElectricityDemandRate,
        FacilityTotalHVACElectricityDemandRate,
        FacilityTotalProducedElectricityEnergy,
        FacilityTotalProducedElectricityRate,
        FacilityTotalPurchasedElectricityEnergy,
        FacilityTotalPurchasedElectricityRate,
        FacilityTotalSurplusElectricityEnergy,
        FacilityTotalSurplusElectricityRate,
        HVACSystemSolverIterationCount,
        HVACSystemTotalHeatRejectionEnergy,
        LightsConvectiveHeatingEnergy,
        LightsConvectiveHeatingRate,
        LightsElectricityEnergy,
        LightsElectricityRate,
        LightsRadiantHeatingEnergy,
        LightsRadiantHeatingRate,
        LightsReturnAirHeatingEnergy,
        LightsReturnAirHeatingRate,
        LightsTotalHeatingEnergy,
        LightsTotalHeatingRate,
        LightsVisibleRadiationHeatingEnergy,
        LightsVisibleRadiationHeatingRate,
        PeopleAirRelativeHumidity,
        PeopleAirTemperature,
        PeopleConvectiveHeatingEnergy,
        PeopleConvectiveHeatingRate,
        PeopleLatentGainEnergy,
        PeopleLatentGainRate,
        PeopleOccupantCount,
        PeopleRadiantHeatingEnergy,
        PeopleRadiantHeatingRate,
        PeopleSensibleHeatingEnergy,
        PeopleSensibleHeatingRate,
        PeopleTotalHeatingEnergy,
        PeopleTotalHeatingRate,
        ScheduleValue,
        SiteBeamSolarRadiationLuminousEfficacy,
        SiteDayTypeIndex,
        SiteDaylightSavingTimeStatus,
        SiteDaylightingModelSkyBrightness,
        SiteDaylightingModelSkyClearness,
        SiteDeepGroundTemperature,
        SiteDiffuseSolarRadiationRateperArea,
        SiteDirectSolarRadiationRateperArea,
        SiteExteriorBeamNormalIlluminance,
        SiteExteriorHorizontalBeamIlluminance,
        SiteExteriorHorizontalSkyIlluminance,
        SiteGroundReflectedSolarRadiationRateperArea,
        SiteGroundTemperature,
        SiteHorizontalInfraredRadiationRateperArea,
        SiteMainsWaterTemperature,
        SiteOpaqueSkyCover,
        SiteOutdoorAirBarometricPressure,
        SiteOutdoorAirDensity,
        SiteOutdoorAirDewpointTemperature,
        SiteOutdoorAirDrybulbTemperature,
        SiteOutdoorAirEnthalpy,
        SiteOutdoorAirHumidityRatio,
        SiteOutdoorAirRelativeHumidity,
        SiteOutdoorAirWetbulbTemperature,
        SitePrecipitationDepth,
        SiteRainStatus,
        SiteSimpleFactorModelGroundTemperature,
        SiteSkyDiffuseSolarRadiationLuminousEfficacy,
        SiteSkyTemperature,
        SiteSnowonGroundStatus,
        SiteSolarAltitudeAngle,
        SiteSolarAzimuthAngle,
        SiteSolarHourAngle,
        SiteSurfaceGroundTemperature,
        SiteTotalSkyCover,
        SiteTotalSurfaceHeatEmissiontoAir,
        SiteTotalZoneExfiltrationHeatLoss,
        SiteTotalZoneExhaustAirHeatLoss,
        SiteWindDirection,
        SiteWindSpeed,
        SurfaceAnisotropicSkyMultiplier,
        SurfaceAverageFaceConductionHeatGainRate,
        SurfaceAverageFaceConductionHeatLossRate,
        SurfaceAverageFaceConductionHeatTransferEnergy,
        SurfaceAverageFaceConductionHeatTransferRate,
        SurfaceAverageFaceConductionHeatTransferRateperArea,
        SurfaceHeatStorageEnergy,
        SurfaceHeatStorageGainRate,
        SurfaceHeatStorageLossRate,
        SurfaceHeatStorageRate,
        SurfaceHeatStorageRateperArea,
        SurfaceInsideFaceAbsorbedShortwaveRadiationRate,
        SurfaceInsideFaceAdjacentAirTemperature,
        SurfaceInsideFaceBeamSolarRadiationHeatGainRate,
        SurfaceInsideFaceConductionHeatGainRate,
        SurfaceInsideFaceConductionHeatLossRate,
        SurfaceInsideFaceConductionHeatTransferEnergy,
        SurfaceInsideFaceConductionHeatTransferRate,
        SurfaceInsideFaceConductionHeatTransferRateperArea,
        SurfaceInsideFaceConvectionClassificationIndex,
        SurfaceInsideFaceConvectionHeatGainEnergy,
        SurfaceInsideFaceConvectionHeatGainRate,
        SurfaceInsideFaceConvectionHeatGainRateperArea,
        SurfaceInsideFaceConvectionHeatTransferCoefficient,
        SurfaceInsideFaceConvectionModelEquationIndex,
        SurfaceInsideFaceConvectionReferenceAirIndex,
        SurfaceInsideFaceExteriorWindowsIncidentBeamSolarRadiationEnergy,
        SurfaceInsideFaceExteriorWindowsIncidentBeamSolarRadiationRate,
        SurfaceInsideFaceExteriorWindowsIncidentBeamSolarRadiationRateperArea,
        SurfaceInsideFaceHeatSourceGainRateperArea,
        SurfaceInsideFaceInitialTransmittedDiffuseAbsorbedSolarRadiationRate,
        SurfaceInsideFaceInitialTransmittedDiffuseTransmittedOutWindowSolarRadiationRate,
        SurfaceInsideFaceInteriorMovableInsulationTemperature,
        SurfaceInsideFaceInteriorWindowsIncidentBeamSolarRadiationEnergy,
        SurfaceInsideFaceInteriorWindowsIncidentBeamSolarRadiationRate,
        SurfaceInsideFaceInteriorWindowsIncidentBeamSolarRadiationRateperArea,
        SurfaceInsideFaceInternalGainsRadiationHeatGainEnergy,
        SurfaceInsideFaceInternalGainsRadiationHeatGainRate,
        SurfaceInsideFaceInternalGainsRadiationHeatGainRateperArea,
        SurfaceInsideFaceLightsRadiationHeatGainEnergy,
        SurfaceInsideFaceLightsRadiationHeatGainRate,
        SurfaceInsideFaceLightsRadiationHeatGainRateperArea,
        SurfaceInsideFaceNetSurfaceThermalRadiationHeatGainEnergy,
        SurfaceInsideFaceNetSurfaceThermalRadiationHeatGainRate,
        SurfaceInsideFaceNetSurfaceThermalRadiationHeatGainRateperArea,
        SurfaceInsideFaceSolarRadiationHeatGainEnergy,
        SurfaceInsideFaceSolarRadiationHeatGainRate,
        SurfaceInsideFaceSolarRadiationHeatGainRateperArea,
        SurfaceInsideFaceSystemRadiationHeatGainEnergy,
        SurfaceInsideFaceSystemRadiationHeatGainRate,
        SurfaceInsideFaceSystemRadiationHeatGainRateperArea,
        SurfaceInsideFaceTemperature,
        SurfaceOutsideFaceBeamSolarIncidentAngleCosineValue,
        SurfaceOutsideFaceConductionHeatGainRate,
        SurfaceOutsideFaceConductionHeatLossRate,
        SurfaceOutsideFaceConductionHeatTransferEnergy,
        SurfaceOutsideFaceConductionHeatTransferRate,
        SurfaceOutsideFaceConductionHeatTransferRateperArea,
        SurfaceOutsideFaceConvectionClassificationIndex,
        SurfaceOutsideFaceConvectionHeatGainEnergy,
        SurfaceOutsideFaceConvectionHeatGainRate,
        SurfaceOutsideFaceConvectionHeatGainRateperArea,
        SurfaceOutsideFaceConvectionHeatTransferCoefficient,
        SurfaceOutsideFaceForcedConvectionModelEquationIndex,
        SurfaceOutsideFaceHeatEmissiontoAirRate,
        SurfaceOutsideFaceHeatSourceGainRateperArea,
        SurfaceOutsideFaceIncidentBeamSolarRadiationRateperArea,
        SurfaceOutsideFaceIncidentBeamToBeamSurfaceReflectedSolarRadiationRateperArea,
        SurfaceOutsideFaceIncidentBeamToDiffuseGroundReflectedSolarRadiationRateperArea,
        SurfaceOutsideFaceIncidentBeamToDiffuseSurfaceReflectedSolarRadiationRateperArea,
        SurfaceOutsideFaceIncidentGroundDiffuseSolarRadiationRateperArea,
        SurfaceOutsideFaceIncidentSkyDiffuseGroundReflectedSolarRadiationRateperArea,
        SurfaceOutsideFaceIncidentSkyDiffuseSolarRadiationRateperArea,
        SurfaceOutsideFaceIncidentSkyDiffuseSurfaceReflectedSolarRadiationRateperArea,
        SurfaceOutsideFaceIncidentSolarRadiationRateperArea,
        SurfaceOutsideFaceNaturalConvectionModelEquationIndex,
        SurfaceOutsideFaceNetThermalRadiationHeatGainEnergy,
        SurfaceOutsideFaceNetThermalRadiationHeatGainRate,
        SurfaceOutsideFaceNetThermalRadiationHeatGainRateperArea,
        SurfaceOutsideFaceOutdoorAirDrybulbTemperature,
        SurfaceOutsideFaceOutdoorAirWetbulbTemperature,
        SurfaceOutsideFaceOutdoorAirWindDirection,
        SurfaceOutsideFaceOutdoorAirWindSpeed,
        SurfaceOutsideFaceSolarRadiationHeatGainEnergy,
        SurfaceOutsideFaceSolarRadiationHeatGainRate,
        SurfaceOutsideFaceSolarRadiationHeatGainRateperArea,
        SurfaceOutsideFaceSunlitArea,
        SurfaceOutsideFaceSunlitFraction,
        SurfaceOutsideFaceTemperature,
        SurfaceOutsideFaceThermalRadiationtoAirHeatTransferCoefficient,
        SurfaceOutsideFaceThermalRadiationtoAirHeatTransferRate,
        SurfaceOutsideFaceThermalRadiationtoGroundHeatTransferCoefficient,
        SurfaceOutsideFaceThermalRadiationtoSkyHeatTransferCoefficient,
        SurfaceOutsideNormalAzimuthAngle,
        SurfaceShadingDeviceIsOnTimeFraction,
        SurfaceStormWindowOnOffStatus,
        SurfaceWindowBackFaceTemperatureLayer1,
        SurfaceWindowBlindSlatAngle,
        SurfaceWindowBSDFBeamDirectionNumber,
        SurfaceWindowBSDFBeamPhiAngle,
        SurfaceWindowBSDFBeamThetaAngle,
        SurfaceWindowFrontFaceTemperatureLayer1,
        SurfaceWindowGapConvectiveHeatTransferEnergy,
        SurfaceWindowGapConvectiveHeatTransferRate,
        SurfaceWindowGlazingBeamtoBeamSolarTransmittance,
        SurfaceWindowGlazingBeamtoDiffuseSolarTransmittance,
        SurfaceWindowGlazingDiffusetoDiffuseSolarTransmittance,
        SurfaceWindowHeatGainEnergy,
        SurfaceWindowHeatGainRate,
        SurfaceWindowHeatLossEnergy,
        SurfaceWindowHeatLossRate,
        SurfaceWindowInsideFaceDividerCondensationStatus,
        SurfaceWindowInsideFaceFrameCondensationStatus,
        SurfaceWindowInsideFaceGlazingCondensationStatus,
        SurfaceWindowModelSolverIterationCount,
        SurfaceWindowNetHeatTransferEnergy,
        SurfaceWindowNetHeatTransferRate,
        SurfaceWindowOutsideRevealReflectedBeamSolarRadiationEnergy,
        SurfaceWindowOutsideRevealReflectedBeamSolarRadiationRate,
        SurfaceWindowShadingDeviceAbsorbedSolarRadiationEnergy,
        SurfaceWindowShadingDeviceAbsorbedSolarRadiationRate,
        SurfaceWindowSolarHorizontalProfileAngle,
        SurfaceWindowSolarVerticalProfileAngle,
        SurfaceWindowSystemSolarAbsorptance,
        SurfaceWindowSystemSolarReflectance,
        SurfaceWindowSystemSolarTransmittance,
        SurfaceWindowTotalGlazingLayersAbsorbedShortwaveRadiationRate,
        SurfaceWindowTotalGlazingLayersAbsorbedSolarRadiationEnergy,
        SurfaceWindowTotalGlazingLayersAbsorbedSolarRadiationRate,
        SurfaceWindowTransmittedBeamSolarRadiationEnergy,
        SurfaceWindowTransmittedBeamSolarRadiationRate,
        SurfaceWindowTransmittedBeamToBeamSolarRadiationEnergy,
        SurfaceWindowTransmittedBeamToBeamSolarRadiationRate,
        SurfaceWindowTransmittedBeamToDiffuseSolarRadiationEnergy,
        SurfaceWindowTransmittedBeamToDiffuseSolarRadiationRate,
        SurfaceWindowTransmittedDiffuseSolarRadiationEnergy,
        SurfaceWindowTransmittedDiffuseSolarRadiationRate,
        SurfaceWindowTransmittedSolarRadiationEnergy,
        SurfaceWindowTransmittedSolarRadiationRate,
        SystemNodeCurrentDensity,
        SystemNodeCurrentDensityVolumeFlowRate,
        SystemNodeDewpointTemperature,
        SystemNodeEnthalpy,
        SystemNodeHeight,
        SystemNodeHumidityRatio,
        SystemNodeMassFlowRate,
        SystemNodePressure,
        SystemNodeQuality,
        SystemNodeRelativeHumidity,
        SystemNodeSetpointHighTemperature,
        SystemNodeSetpointHumidityRatio,
        SystemNodeSetpointLowTemperature,
        SystemNodeSetpointMaximumHumidityRatio,
        SystemNodeSetpointMinimumHumidityRatio,
        SystemNodeSetpointTemperature,
        SystemNodeSpecificHeat,
        SystemNodeStandardDensityVolumeFlowRate,
        SystemNodeTemperature,
        SystemNodeWetbulbTemperature,
        SystemNodeWindDirection,
        SystemNodeWindSpeed,
        ZoneAdaptiveComfortOperativeTemperatureSetPoint,
        ZoneAirHeatBalanceAirEnergyStorageRate,
        ZoneAirHeatBalanceInternalConvectiveHeatGainRate,
        ZoneAirHeatBalanceInterzoneAirTransferRate,
        ZoneAirHeatBalanceOutdoorAirTransferRate,
        ZoneAirHeatBalanceSurfaceConvectionRate,
        ZoneAirHeatBalanceSystemAirTransferRate,
        ZoneAirHeatBalanceSystemConvectiveHeatGainRate,
        ZoneAirHumidityRatio,
        ZoneAirRelativeHumidity,
        ZoneAirSystemSensibleCoolingEnergy,
        ZoneAirSystemSensibleCoolingRate,
        ZoneAirSystemSensibleHeatingEnergy,
        ZoneAirSystemSensibleHeatingRate,
        ZoneAirTemperature,
        ZoneCoolingSetpointNotMetTime,
        ZoneCoolingSetpointNotMetWhileOccupiedTime,
        ZoneElectricEquipmentConvectiveHeatingEnergy,
        ZoneElectricEquipmentConvectiveHeatingRate,
        ZoneElectricEquipmentElectricityEnergy,
        ZoneElectricEquipmentElectricityRate,
        ZoneElectricEquipmentLatentGainEnergy,
        ZoneElectricEquipmentLatentGainRate,
        ZoneElectricEquipmentLostHeatEnergy,
        ZoneElectricEquipmentLostHeatRate,
        ZoneElectricEquipmentRadiantHeatingEnergy,
        ZoneElectricEquipmentRadiantHeatingRate,
        ZoneElectricEquipmentTotalHeatingEnergy,
        ZoneElectricEquipmentTotalHeatingRate,
        ZoneExfiltrationHeatTransferRate,
        ZoneExfiltrationLatentHeatTransferRate,
        ZoneExfiltrationSensibleHeatTransferRate,
        ZoneExhaustAirHeatTransferRate,
        ZoneExhaustAirLatentHeatTransferRate,
        ZoneExhaustAirSensibleHeatTransferRate,
        ZoneExteriorWindowsTotalTransmittedBeamSolarRadiationEnergy,
        ZoneExteriorWindowsTotalTransmittedBeamSolarRadiationRate,
        ZoneExteriorWindowsTotalTransmittedDiffuseSolarRadiationEnergy,
        ZoneExteriorWindowsTotalTransmittedDiffuseSolarRadiationRate,
        ZoneHeatIndex,
        ZoneHeatingSetpointNotMetTime,
        ZoneHeatingSetpointNotMetWhileOccupiedTime,
        ZoneHumidityIndex,
        ZoneIdealLoadsEconomizerActiveTime,
        ZoneIdealLoadsHeatRecoveryActiveTime,
        ZoneIdealLoadsHeatRecoveryLatentCoolingEnergy,
        ZoneIdealLoadsHeatRecoveryLatentCoolingRate,
        ZoneIdealLoadsHeatRecoveryLatentHeatingEnergy,
        ZoneIdealLoadsHeatRecoveryLatentHeatingRate,
        ZoneIdealLoadsHeatRecoverySensibleCoolingEnergy,
        ZoneIdealLoadsHeatRecoverySensibleCoolingRate,
        ZoneIdealLoadsHeatRecoverySensibleHeatingEnergy,
        ZoneIdealLoadsHeatRecoverySensibleHeatingRate,
        ZoneIdealLoadsHeatRecoveryTotalCoolingEnergy,
        ZoneIdealLoadsHeatRecoveryTotalCoolingRate,
        ZoneIdealLoadsHeatRecoveryTotalHeatingEnergy,
        ZoneIdealLoadsHeatRecoveryTotalHeatingRate,
        ZoneIdealLoadsHybridVentilationAvailableStatus,
        ZoneIdealLoadsMixedAirHumidityRatio,
        ZoneIdealLoadsMixedAirTemperature,
        ZoneIdealLoadsOutdoorAirLatentCoolingEnergy,
        ZoneIdealLoadsOutdoorAirLatentCoolingRate,
        ZoneIdealLoadsOutdoorAirLatentHeatingEnergy,
        ZoneIdealLoadsOutdoorAirLatentHeatingRate,
        ZoneIdealLoadsOutdoorAirMassFlowRate,
        ZoneIdealLoadsOutdoorAirSensibleCoolingEnergy,
        ZoneIdealLoadsOutdoorAirSensibleCoolingRate,
        ZoneIdealLoadsOutdoorAirSensibleHeatingEnergy,
        ZoneIdealLoadsOutdoorAirSensibleHeatingRate,
        ZoneIdealLoadsOutdoorAirStandardDensityVolumeFlowRate,
        ZoneIdealLoadsOutdoorAirTotalCoolingEnergy,
        ZoneIdealLoadsOutdoorAirTotalCoolingRate,
        ZoneIdealLoadsOutdoorAirTotalHeatingEnergy,
        ZoneIdealLoadsOutdoorAirTotalHeatingRate,
        ZoneIdealLoadsSupplyAirHumidityRatio,
        ZoneIdealLoadsSupplyAirLatentCoolingEnergy,
        ZoneIdealLoadsSupplyAirLatentCoolingRate,
        ZoneIdealLoadsSupplyAirLatentHeatingEnergy,
        ZoneIdealLoadsSupplyAirLatentHeatingRate,
        ZoneIdealLoadsSupplyAirMassFlowRate,
        ZoneIdealLoadsSupplyAirSensibleCoolingEnergy,
        ZoneIdealLoadsSupplyAirSensibleCoolingRate,
        ZoneIdealLoadsSupplyAirSensibleHeatingEnergy,
        ZoneIdealLoadsSupplyAirSensibleHeatingRate,
        ZoneIdealLoadsSupplyAirStandardDensityVolumeFlowRate,
        ZoneIdealLoadsSupplyAirTemperature,
        ZoneIdealLoadsSupplyAirTotalCoolingEnergy,
        ZoneIdealLoadsSupplyAirTotalCoolingRate,
        ZoneIdealLoadsSupplyAirTotalHeatingEnergy,
        ZoneIdealLoadsSupplyAirTotalHeatingRate,
        ZoneIdealLoadsZoneLatentCoolingEnergy,
        ZoneIdealLoadsZoneLatentCoolingRate,
        ZoneIdealLoadsZoneLatentHeatingEnergy,
        ZoneIdealLoadsZoneLatentHeatingRate,
        ZoneIdealLoadsZoneSensibleCoolingEnergy,
        ZoneIdealLoadsZoneSensibleCoolingRate,
        ZoneIdealLoadsZoneSensibleHeatingEnergy,
        ZoneIdealLoadsZoneSensibleHeatingRate,
        ZoneIdealLoadsZoneTotalCoolingEnergy,
        ZoneIdealLoadsZoneTotalCoolingRate,
        ZoneIdealLoadsZoneTotalHeatingEnergy,
        ZoneIdealLoadsZoneTotalHeatingRate,
        ZoneInfiltrationAirChangeRate,
        ZoneInfiltrationCurrentDensityVolume,
        ZoneInfiltrationCurrentDensityVolumeFlowRate,
        ZoneInfiltrationLatentHeatGainEnergy,
        ZoneInfiltrationLatentHeatLossEnergy,
        ZoneInfiltrationMass,
        ZoneInfiltrationMassFlowRate,
        ZoneInfiltrationSensibleHeatGainEnergy,
        ZoneInfiltrationSensibleHeatLossEnergy,
        ZoneInfiltrationStandardDensityVolume,
        ZoneInfiltrationStandardDensityVolumeFlowRate,
        ZoneInfiltrationTotalHeatGainEnergy,
        ZoneInfiltrationTotalHeatLossEnergy,
        ZoneInteriorWindowsTotalTransmittedBeamSolarRadiationEnergy,
        ZoneInteriorWindowsTotalTransmittedBeamSolarRadiationRate,
        ZoneInteriorWindowsTotalTransmittedDiffuseSolarRadiationEnergy,
        ZoneInteriorWindowsTotalTransmittedDiffuseSolarRadiationRate,
        ZoneLightsConvectiveHeatingEnergy,
        ZoneLightsConvectiveHeatingRate,
        ZoneLightsElectricityEnergy,
        ZoneLightsElectricityRate,
        ZoneLightsRadiantHeatingEnergy,
        ZoneLightsRadiantHeatingRate,
        ZoneLightsReturnAirHeatingEnergy,
        ZoneLightsReturnAirHeatingRate,
        ZoneLightsTotalHeatingEnergy,
        ZoneLightsTotalHeatingRate,
        ZoneLightsVisibleRadiationHeatingEnergy,
        ZoneLightsVisibleRadiationHeatingRate,
        ZoneMeanAirDewpointTemperature,
        ZoneMeanAirHumidityRatio,
        ZoneMeanAirTemperature,
        ZoneMeanRadiantTemperature,
        ZoneMechanicalVentilationAirChangesperHour,
        ZoneMechanicalVentilationCoolingLoadDecreaseEnergy,
        ZoneMechanicalVentilationCoolingLoadIncreaseDuetoOverheatingEnergy,
        ZoneMechanicalVentilationCoolingLoadIncreaseEnergy,
        ZoneMechanicalVentilationCurrentDensityVolume,
        ZoneMechanicalVentilationCurrentDensityVolumeFlowRate,
        ZoneMechanicalVentilationHeatingLoadDecreaseEnergy,
        ZoneMechanicalVentilationHeatingLoadIncreaseDuetoOvercoolingEnergy,
        ZoneMechanicalVentilationHeatingLoadIncreaseEnergy,
        ZoneMechanicalVentilationMass,
        ZoneMechanicalVentilationMassFlowRate,
        ZoneMechanicalVentilationNoLoadHeatAdditionEnergy,
        ZoneMechanicalVentilationNoLoadHeatRemovalEnergy,
        ZoneMechanicalVentilationStandardDensityVolume,
        ZoneMechanicalVentilationStandardDensityVolumeFlowRate,
        ZoneOperativeTemperature,
        ZoneOscillatingTemperaturesDuringOccupancyTime,
        ZoneOscillatingTemperaturesinDeadbandTime,
        ZoneOscillatingTemperaturesTime,
        ZoneOutdoorAirDrybulbTemperature,
        ZoneOutdoorAirWetbulbTemperature,
        ZoneOutdoorAirWindDirection,
        ZoneOutdoorAirWindSpeed,
        ZonePeopleConvectiveHeatingEnergy,
        ZonePeopleConvectiveHeatingRate,
        ZonePeopleLatentGainEnergy,
        ZonePeopleLatentGainRate,
        ZonePeopleOccupantCount,
        ZonePeopleRadiantHeatingEnergy,
        ZonePeopleRadiantHeatingRate,
        ZonePeopleSensibleHeatingEnergy,
        ZonePeopleSensibleHeatingRate,
        ZonePeopleTotalHeatingEnergy,
        ZonePeopleTotalHeatingRate,
        ZonePredictedMoistureLoadMoistureTransferRate,
        ZonePredictedMoistureLoadtoDehumidifyingSetpointMoistureTransferRate,
        ZonePredictedMoistureLoadtoHumidifyingSetpointMoistureTransferRate,
        ZonePredictedSensibleLoadRoomAirCorrectionFactor,
        ZonePredictedSensibleLoadtoCoolingSetpointHeatTransferRate,
        ZonePredictedSensibleLoadtoHeatingSetpointHeatTransferRate,
        ZonePredictedSensibleLoadtoSetpointHeatTransferRate,
        ZoneSystemPredictedMoistureLoadMoistureTransferRate,
        ZoneSystemPredictedMoistureLoadtoDehumidifyingSetpointMoistureTransferRate,
        ZoneSystemPredictedMoistureLoadtoHumidifyingSetpointMoistureTransferRate,
        ZoneSystemPredictedSensibleLoadtoCoolingSetpointHeatTransferRate,
        ZoneSystemPredictedSensibleLoadtoHeatingSetpointHeatTransferRate,
        ZoneSystemPredictedSensibleLoadtoSetpointHeatTransferRate,
        ZoneTargetVozVentilationFlowRate,
        ZoneThermalComfortASHRAE55SimpleModelSummerClothesNotComfortableTime,
        ZoneThermalComfortASHRAE55SimpleModelSummerorWinterClothesNotComfortableTime,
        ZoneThermalComfortASHRAE55SimpleModelWinterClothesNotComfortableTime,
        ZoneThermostatAirTemperature,
        ZoneThermostatControlType,
        ZoneThermostatCoolingSetpointTemperature,
        ZoneThermostatHeatingSetpointTemperature,
        ZoneTotalInternalConvectiveHeatingEnergy,
        ZoneTotalInternalConvectiveHeatingRate,
        ZoneTotalInternalLatentGainEnergy,
        ZoneTotalInternalLatentGainRate,
        ZoneTotalInternalRadiantHeatingEnergy,
        ZoneTotalInternalRadiantHeatingRate,
        ZoneTotalInternalTotalHeatingEnergy,
        ZoneTotalInternalTotalHeatingRate,
        ZoneTotalInternalVisibleRadiationHeatingEnergy,
        ZoneTotalInternalVisibleRadiationHeatingRate,
        ZoneVentilationAboveTargetVozTime,
        ZoneVentilationAirChangeRate,
        ZoneVentilationAirInletTemperature,
        ZoneVentilationAtTargetVozTime,
        ZoneVentilationBelowTargetVozTime,
        ZoneVentilationCurrentDensityVolume,
        ZoneVentilationCurrentDensityVolumeFlowRate,
        ZoneVentilationFanElectricityEnergy,
        ZoneVentilationLatentHeatGainEnergy,
        ZoneVentilationLatentHeatLossEnergy,
        ZoneVentilationMass,
        ZoneVentilationMassFlowRate,
        ZoneVentilationSensibleHeatGainEnergy,
        ZoneVentilationSensibleHeatLossEnergy,
        ZoneVentilationStandardDensityVolume,
        ZoneVentilationStandardDensityVolumeFlowRate,
        ZoneVentilationTotalHeatGainEnergy,
        ZoneVentilationTotalHeatLossEnergy,
        ZoneVentilationWhenUnoccupiedTime,
        ZoneWindowsTotalHeatGainEnergy,
        ZoneWindowsTotalHeatGainRate,
        ZoneWindowsTotalHeatLossEnergy,
        ZoneWindowsTotalHeatLossRate,
        ZoneWindowsTotalTransmittedSolarRadiationEnergy,
        ZoneWindowsTotalTransmittedSolarRadiationRate

    }

    public enum ReportingFrequencyType
    {
        Timestep,
        Hourly,
        Detailed,
        Daily,
        Monthly,
        RunPeriod,
        Environment,
        Annual
    }
    public class OutputVariable
    {
        private string _keyValue;
        public string KeyValue
        {
            get => _keyValue;
            set => _keyValue = value;
        }

        private VariableNameType? _variableName;
        public string VariableName
        {
            get => Tool.UnPascalCase(_variableName.ToString());
            set
            {
                object variableNameObject;
                if (Enum.TryParse(typeof(VariableNameType), value.Replace(" ", ""), out variableNameObject))
                {
                    _variableName = (VariableNameType)Enum.Parse(typeof(VariableNameType), value.Replace(" ", ""), true);
                }
            }

        }

        private ReportingFrequencyType? _reportingFrequency;
        public ReportingFrequencyType? ReportingFrequency
        {
            get => _reportingFrequency;
            set => _reportingFrequency = value;
        }

        private string _scheduleName;
        public string ScheduleName
        {
            get => _scheduleName;
            set => _scheduleName = value;
        }


        public OutputVariable() { }
        private static List<OutputVariable> list = new List<OutputVariable>();

        public static void Add(OutputVariable outputVariable)
        {
            list.Add(outputVariable);

            Errors er = new Errors();
            if (outputVariable._variableName == null)
            {
                er.Class = "Output:Variable";
                er.Field = "VariableName";
                Errors.Add(er);
            }
        }
        private static string[] Read()
        {
            string[] print = new string[list.Count];
            for (int i = 0; i < list.Count; i++)
            {
                print[i] = $"Output:Variable,\n" +
                    ($"  {list[i].KeyValue}" + ",").PadRight(27, ' ') + " !-Key Value\n" +
                    ($"  {list[i].VariableName}" + ",").PadRight(27, ' ') + " !-Variable Name\n" +
                    ($"  {list[i].ReportingFrequency}" + ",").PadRight(27, ' ') + " !-Reporting Frequency\n" +
                    ($"  {list[i].ScheduleName}" + ";").PadRight(27, ' ') + " !-Schedule Name";

            }

            return print;
        }

        public static void Get(string idfFile)
        {
            using (StreamWriter sw = File.AppendText(idfFile))
            {
                foreach (string line in OutputVariable.Read())
                {
                    sw.WriteLine(line);
                }
            }

        }

        public static void Get()
        {
            
            foreach (string line in OutputVariable.Read())
            {
                Console.WriteLine(line);
            }
            

        }
        public static void Clear()
        {
            list.Clear();
        }
    }
}
